//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/3/2025 6:52:36 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Business
{
    public partial class Transaction {

        public Transaction()
        {
            this.TransactionItems = new List<TransactionItem>();
            OnCreated();
        }

        public short transactionId { get; set; }

        public short customerId { get; set; }

        public DateTime date { get; set; }

        public int amount { get; set; }

        public string status { get; set; }


        public virtual Customer Customer { get; set; }


        public virtual IList<TransactionItem> TransactionItems { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
