//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/3/2025 5:40:31 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Business
{
    public partial class TransactionItem {

        public TransactionItem()
        {
            OnCreated();
        }

        public short transactionItemId { get; set; }

        public short transactionId { get; set; }

        public short productId { get; set; }

        public short quantity { get; set; }

        public short TransactiontransactionId { get; set; }

        public short ProductproductId { get; set; }


        public virtual Transaction Transaction { get; set; }


        public virtual Product Product1 { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
