//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/3/2025 1:55:10 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Configuration;

namespace Business
{

    public partial class cnBusiness : DbContext
    {

        public cnBusiness() :
            base()
        {
            OnCreated();
        }

        public cnBusiness(DbContextOptions<cnBusiness> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            
            if (!optionsBuilder.IsConfigured || (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) && !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;AttachDbFileName=C:\\Users\\bruhajuj\\Btm.mdf;Integrated Security=True");
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        private static string GetConnectionString(string connectionStringName)
        {
            var configurationBuilder = new ConfigurationBuilder().AddJsonFile("appsettings.json", optional: true, reloadOnChange: false);
            var configuration = configurationBuilder.Build();
            return configuration.GetConnectionString(connectionStringName);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<Customer> Customers
        {
            get;
            set;
        }

        public virtual DbSet<Product> Products
        {
            get;
            set;
        }

        public virtual DbSet<Transaction> Transactions
        {
            get;
            set;
        }

        public virtual DbSet<TransactionItem> TransactionItems
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            this.CustomerMapping(modelBuilder);
            this.CustomizeCustomerMapping(modelBuilder);

            this.ProductMapping(modelBuilder);
            this.CustomizeProductMapping(modelBuilder);

            this.TransactionMapping(modelBuilder);
            this.CustomizeTransactionMapping(modelBuilder);

            this.TransactionItemMapping(modelBuilder);
            this.CustomizeTransactionItemMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region Customer Mapping

        private void CustomerMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Customer>().ToTable(@"Customers");
            modelBuilder.Entity<Customer>().Property(x => x.customerId).HasColumnName(@"customerId").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Customer>().Property(x => x.name).HasColumnName(@"name").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Customer>().Property(x => x.email).HasColumnName(@"email").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Customer>().Property(x => x.phone).HasColumnName(@"phone").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Customer>().HasKey(@"customerId");
        }

        partial void CustomizeCustomerMapping(ModelBuilder modelBuilder);

        #endregion

        #region Product Mapping

        private void ProductMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Product>().ToTable(@"Products");
            modelBuilder.Entity<Product>().Property(x => x.productId).HasColumnName(@"productId").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Product>().Property(x => x.name).HasColumnName(@"name").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Product>().Property(x => x.price).HasColumnName(@"price").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Product>().HasKey(@"productId");
        }

        partial void CustomizeProductMapping(ModelBuilder modelBuilder);

        #endregion

        #region Transaction Mapping

        private void TransactionMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Transaction>().ToTable(@"Transactions");
            modelBuilder.Entity<Transaction>().Property(x => x.transactionId).HasColumnName(@"transactionId").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Transaction>().Property(x => x.customerId).HasColumnName(@"customerId").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Transaction>().Property(x => x.date).HasColumnName(@"date").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Transaction>().Property(x => x.amount).HasColumnName(@"amount").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Transaction>().Property(x => x.status).HasColumnName(@"status").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Transaction>().Property(x => x.CustomercustomerId).HasColumnName(@"CustomercustomerId").ValueGeneratedNever();
            modelBuilder.Entity<Transaction>().HasKey(@"transactionId");
        }

        partial void CustomizeTransactionMapping(ModelBuilder modelBuilder);

        #endregion

        #region TransactionItem Mapping

        private void TransactionItemMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TransactionItem>().ToTable(@"TransactionItems");
            modelBuilder.Entity<TransactionItem>().Property(x => x.transactionItemId).HasColumnName(@"transactionItemId").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<TransactionItem>().Property(x => x.transactionId).HasColumnName(@"transactionId").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<TransactionItem>().Property(x => x.productId).HasColumnName(@"productId").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<TransactionItem>().Property(x => x.quantity).HasColumnName(@"quantity").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<TransactionItem>().Property(x => x.TransactiontransactionId).HasColumnName(@"TransactiontransactionId").ValueGeneratedNever();
            modelBuilder.Entity<TransactionItem>().Property(x => x.ProductproductId).HasColumnName(@"ProductproductId").ValueGeneratedNever();
            modelBuilder.Entity<TransactionItem>().HasKey(@"transactionItemId");
        }

        partial void CustomizeTransactionItemMapping(ModelBuilder modelBuilder);

        #endregion

        private void RelationshipsMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Customer>().HasMany(x => x.Transactions).WithOne(op => op.Customer).HasForeignKey(@"customerId").IsRequired(true);

            modelBuilder.Entity<Product>().HasMany(x => x.TransactionItems).WithOne(op => op.Product1).HasForeignKey(@"productId").IsRequired(true);

            modelBuilder.Entity<Transaction>().HasOne(x => x.Customer).WithMany(op => op.Transactions).HasForeignKey(@"customerId").IsRequired(true);
            modelBuilder.Entity<Transaction>().HasMany(x => x.TransactionItems).WithOne(op => op.Transaction).HasForeignKey(@"transactionId").IsRequired(true);

            modelBuilder.Entity<TransactionItem>().HasOne(x => x.Transaction).WithMany(op => op.TransactionItems).HasForeignKey(@"transactionId").IsRequired(true);
            modelBuilder.Entity<TransactionItem>().HasOne(x => x.Product1).WithMany(op => op.TransactionItems).HasForeignKey(@"productId").IsRequired(true);
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
